### ISSUE TITLE
Any documentation/guides?

### ISSUE THREAD

**Issue by blueberry** [OpenGamma/OG-Maths#142]
Hi,

I am trying to evaluate OG-Maths for possible use as it seems to fit some of the needs of my project, but I  did not find ANY guide on how to use it. Yes, it is clear that it is included in the project via mavaen, but how to actually use it?
What are the functions, what are their parameters, what interfaces/classes they are in?
Is there at least a working hello world?

**Comment by stuartarchibald** [comment]
Hi @blueberry,

Thanks for your interest in OG-Maths. As you may have noted on the OG-Maths landing page it is currently at a version less than 1.0, largely because it is in active development and testing. Good news is that we are through the first large scale test and everything seems ok, however it really is beta software in the traditional sense of beta!

In the coming months as the APIs etc. become more concrete, documentation (which is largely in staging) will be made available. Until then, if you want to have a play, the unit tests for the DOGMA class (the main entry point from java) will probably give you the best start from what is presently available, see https://github.com/OpenGamma/OG-Maths/blob/master/src/java/src/test/java/com/opengamma/maths/DOGMATest.java .

Should you wish to give it a try, we'd welcome your feedback.

Thanks.

**Comment by blueberry** [comment]
Thank you for the info.

**Comment by stuartarchibald** [comment]
Closing issues as resolved. Thanks for the query.
